#!/bin/sh
#
# Backup SSH keys to the SD card
#

source /etc/bootvars.conf

source /etc/init.d/start_only.sh

SD_KEYDIR=${_SD_ROOT}/sshkeys
ETC_KEYDIRS="/etc/ssh /etc/dropbear"

if [ "${_SYS_PERSISTENT_FILESYSTEM}" == "false" ]; then
        for d in $ETC_KEYDIRS ; do
                if [ ! -d ${d} ]; then
                        continue;
                fi
                KEYFOLDER=$SD_KEYDIR/$(basename ${d})
                echo "### Backup keys from $d to the SD card: ${KEYFOLDER}"
                if [ ! -d $KEYFOLDER ]; then
                        mkdir -p $KEYFOLDER
                fi
                sshkeys=$(find ${d} -type f -name "*host_*key*")
                for k in ${sshkeys}; do
                        cp ${k} $KEYFOLDER
                done
        done
        sync
        echo "OK"
fi

exit 0
