#!/bin/sh
#
# Restores SSH keys from the SD card
#

source /etc/bootvars.conf

source /etc/init.d/start_only.sh

if [ "$_SYS_PERSISTENT_FILESYSTEM" == "true" ]; then
    UPDATE=mv
else
    UPDATE=cp
fi

SD_KEYDIR=${_SD_ROOT}/sshkeys
ETC_KEYDIRS="/etc/ssh /etc/dropbear"

if [ -d $SD_KEYDIR ]; then
        for d in $ETC_KEYDIRS ; do
                if [ ! -d ${d} ]; then
                        continue;
                fi
                KEYFOLDER=$SD_KEYDIR/$(basename ${d})
                echo -n "### Restoring SSH keys from the ${SD_KEYDIR} to ${d}..."
                sshkeys=$(find ${KEYFOLDER} -type f -name "*host_*key*")
                for k in ${sshkeys}; do
                        ${UPDATE} -f ${k} ${d}/
                        chmod 600 $d/*host_*key*
                done
                if [ "$_SYS_PERSISTENT_FILESYSTEM" == "true" ]; then
                        rm -rf $SD_KEYDIR
                fi
        done
        echo "OK"
fi

exit 0
