#!/bin/sh
#
# Mount SD card partition
#

_SD_ROOT=/dev/mmcblk0p1

if [ -f /etc/init.d/start_only.sh ]
then
	source /etc/init.d/start_only.sh
else
	source /usr/sbin/start_only.sh
fi 


mounted=$(mount | grep "${_SD_ROOT}")
if [ "$mounted" == "" ] && [ "${_SD_ROOT}" != "" ] ; then
    echo "+++ Waiting to mount SD card ..."
    i=0
    while [ "$mounted" == "" ] && [ $i -lt 5 ]; do
        sleep 1
        mount -a
        mounted=$(mount | grep ${_SD_ROOT})
        i=$(( i + 1 ))
    done
    if [ "$mounted" != "" ]; then
        echo "+++ SD Card mounted ..."
    else
        echo "ERROR: Failed to mount SD card"
    fi
fi





