#!/bin/sh
#
# Start the network....
#

# UDC (USB Device Controller configuration https://www.kernel.org/doc/html/latest/usb/gadget_configfs.html )
source /etc/bootvars.conf

USB_CONF=$_SD_ROOT/usb_config
GADGET=/sys/kernel/config/usb_gadget/g1
if [ -f "$USB_CONF" ];
then
	source $USB_CONF
fi

# USB_MODE is defined in $USB_CONF which will be added by HDL Verifier APIs for board setup
# Also check if the USB dr_mode is peripheral. In peripheral mode, /sys/class/udc is not empty
#as it lists the USB Device Controller devices.

if [ "$USB_MODE" == "EthernetDevice" ] && [ "$(ls -A /sys/class/udc | wc -l)" -ne 0 ];
then
	echo "### USB_MODE is EthernetDevice"
else
	exit 0
fi

case "$1" in
  start)
 	echo "Starting UDC Gadgets..."
	PRODUCT="Mathworks USB Ethernet/RNDIS Gadget"
	mount -t configfs none /sys/kernel/config
	mkdir -p $GADGET
	echo "creating gadget complete "
	echo "64" > $GADGET/bMaxPacketSize0
	echo "0x200" >  $GADGET/bcdUSB
	echo "0x100" >  $GADGET/bcdDevice
	echo "0x353E" > $GADGET/idVendor
	echo "0x0001" > $GADGET/idProduct
	serial=`dmesg | grep SPI-NOR-UniqueID`
	serial=${serial#*SPI-NOR-UniqueID }
	echo $serial > /etc/serial
	sha1=`echo $serial | sha1sum`
	mkdir -p $GADGET/strings/0x409
	echo "The MathWorks Inc." > $GADGET/strings/0x409/manufacturer
	echo $PRODUCT > $GADGET/strings/0x409/product
	echo $serial > $GADGET/strings/0x409/serialnumber 
	
	mkdir -p $GADGET/functions/rndis.rn0
	echo $HOST_ADDR > $GADGET/functions/rndis.rn0/host_addr
	echo $DEV_ADDR > $GADGET/functions/rndis.rn0/dev_addr
	
	mkdir -p $GADGET/configs/c1.1
	ln -s $GADGET/functions/rndis.rn0 $GADGET/configs/c1.1
	#!/bin/sh
	zynqmpDev=$(find /sys/devices -name "fe200000.dwc3")
	if [ "${zynqmpDev}" != "" ];
	then
		echo "fe200000.dwc3" > $GADGET/UDC
	else
		zynq7000Dev=$(find /sys/devices -name "ci_hdrc.0")
		if [ "${zynq7000Dev}" != "" ];
		then
			echo "ci_hdrc.0" > $GADGET/UDC
		fi
	fi
	ip link set dev usb0 mtu 15300
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	echo -n "Stopping UDC Gadgets..."
	echo " " > $GADGET/UDC
	rm $GADGET/configs/c1.1/rndis.rn0
	rmdir $GADGET/strings/0x409
	rmdir $GADGET/configs/c1.1
	rmdir $GADGET/functions/rndis.rn0
	rmdir $GADGET 2> /dev/null
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?


