#!/bin/sh
#
# Start the usb ethernet....
#
source /etc/bootvars.conf
USB_CONF=$_SD_ROOT/usb_config

if [ "${_SYS_NETWORK_DISABLE}" == "true" ]; then
    echo -n "USB ethernet disabled..."
    exit 0
fi

create_system_files () {
	if [ -f "$USB_CONF" ]
		then
		source $USB_CONF
	fi
	if [ "$USB_MODE" == "EthernetDevice" ] && [ "$(ls -A /sys/class/udc | wc -l)" -ne 0 ]
	then 
		UDHCPD_CONF=/etc/udhcpd.conf
		IFACE=/etc/network/interfaces
		NETMASK=`fw_printenv -n netmask 2> /dev/null || echo 255.255.255.0`
		### Replace /etc/udhcpd.conf ###
		echo "start $USB_IPADDR_HOST" > $UDHCPD_CONF
		echo "end $USB_IPADDR_HOST" >> $UDHCPD_CONF
		echo "interface usb0" >> $UDHCPD_CONF
		echo "option subnet $NETMASK" >> $UDHCPD_CONF
		### /etc/network/interfaces ###
		echo -e "auto usb0\n""iface usb0 inet static" >> $IFAC
		echo -e "\taddress $USB_IPADDR_TARGET\n""\tnetmask $NETMASK\n" >> $IFACE
	else
		exit 0
	fi
}

case "$1" in
  start)
 	echo "Starting USB Ethernet..."
	create_system_files()
	modprobe -a g_ether
	;;
  stop)
	echo "Stopping USB Ethernet..."
	modprobe -r g_ether 2>/dev/null
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

